#定义步骤
kind: pipeline
name: default

services:
- name: database
  image: mysql
  environment:
    MYSQL_DATABASE: feedback
    MYSQL_USER: ymx
    MYSQL_PASSWORD: 123
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

- name: my-image
  image: registry.cn-hangzhou.aliyuncs.com/web-ci/web-build:v1
  commands:
    - nginx -t
    - nginx
    - service nginx status
    - vendor/bin/phpunit --configuration phpunit.xml

steps:
  - name: vue-install test-unit test-e2e
    image: cypress/included:3.2.0
    commands:
      - ls
      - cd /
      - ls
      - curl http://localhost
      - curl http://www.baidu.com
      - cd resources/vue
      - npm install  #--registry https://registry.npm.taobao.org
      - npm run test:unit
      - npm run startOnCI

  - name: vueBuild
    image: node
    commands:
      - ls
      - cd /
      - ls
      - cd /var
      - ls
      - cd resources/vue
      - npm install  #--registry https://registry.npm.taobao.org
      - npm run build
